### ISSUE TITLE
Fix zipping 

### ISSUE THREAD

**Issue by elbuo8** [RebelMail/node-lambda#6]

**Comment by hanchang** [comment]
I'm getting an error message when running `node-lambda deploy`:

    /usr/local/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/request.js:32
              throw err;
                    ^
    Error: ENOENT, no such file or directory '/tmp4b85662b-1b1b-40b1-9e3d-1fb5f2bedf91'
        at Object.fs.rmdirSync (fs.js:624:18)
        at /usr/local/lib/node_modules/node-lambda/lib/main.js:124:14
        at /usr/local/lib/node_modules/node-lambda/node_modules/async/lib/async.js:254:17
        at done (/usr/local/lib/node_modules/node-lambda/node_modules/async/lib/async.js:129:15)
        at /usr/local/lib/node_modules/node-lambda/node_modules/async/lib/async.js:32:16
        at /usr/local/lib/node_modules/node-lambda/node_modules/async/lib/async.js:251:21
        at Response.<anonymous> (/usr/local/lib/node_modules/node-lambda/lib/main.js:120:15)
        at Request.<anonymous> (/usr/local/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/request.js:350:18)
        at Request.callListeners (/usr/local/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/sequential_executor.js:100:18)
        at Request.emit (/usr/local/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/sequential_executor.js:77:10)

However, the function runs successfully locally via `node-lambda run`. Is this what the bug is referring to? If you can provide some more details about what's going on I'd love to help take a look at it.

**Comment by motdotla** [comment]
What version of node-lambda are you on?

**Comment by hanchang** [comment]
Ooh, great question:

    $ node-lambda --version
    0.3.0

I see the latest at the moment is 0.3.13, let me upgrade and see if that fixes the issue, I'll report back here when finished.

**Comment by motdotla** [comment]
bump up to 0.3.13. We had some bugs that were fixed. This was one of them.

**Comment by hanchang** [comment]
Upgrading helped, but now I get the following error message:

    { [NetworkingError: CERT_UNTRUSTED]
      message: 'CERT_UNTRUSTED',
      code: 'NetworkingError',
      region: 'us-east-1',
      hostname: 'lambda.us-east-1.amazonaws.com',
      retryable: true,
      time: Sun Feb 15 2015 21:10:54 GMT-0500 (EST) }

**Comment by motdotla** [comment]
do you have a AWS_ROLE set in your .env file?

**Comment by hanchang** [comment]
Yup, my AWS_ROLE is set correctly in my `.env` file.

After some research, turns out the `CERT_UNTRUSTED` message is either due to node.js v0.10.33 or v0.10.34 but is fixed in 0.10.35+, see - https://github.com/aws/aws-sdk-js/issues/446

This was my problem, I'm upgrading node and will report back how it goes!

**Comment by hanchang** [comment]
Cool, that was the issue, after upgrading Node from 0.10.34 to 0.10.35 the error goes away.
Just for fun I tried 0.12.0 and it didn't seem to work, but I didn't investigate further since at the moment Lambda only supports Node 0.10.x at this point anyways:
http://docs.aws.amazon.com/lambda/latest/dg/lambda-introduction.html#current-supported-versions

**Comment by motdotla** [comment]
Ok, cool. Closing.
